# Generated by Django 4.2.7 on 2023-11-14 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0002_initial'),
        ('turns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='desk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='desks.desk'),
        ),
    ]
