# Generated by Django 4.2.7 on 2023-11-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0002_alter_turn_desk'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='waiting_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
