# Generated by Django 4.2.7 on 2023-11-28 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_personal_id'),
        ('categories', '0001_initial'),
        ('turns', '0003_turn_waiting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='personal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client'),
        ),
    ]
