# Generated by Django 4.2.7 on 2023-11-28 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('priorities', '0002_alter_priority_priority'),
        ('categories', '0001_initial'),
        ('clients', '0003_alter_client_personal_id'),
        ('turns', '0004_alter_turn_category_alter_turn_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='personal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='priorities.priority'),
        ),
    ]
