# Generated by Django 4.2.7 on 2023-12-11 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0005_alter_desk_user'),
        ('turns', '0006_alter_turn_category_alter_turn_personal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='desk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='desks.desk'),
        ),
    ]
