# Generated by Django 4.2.7 on 2023-11-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='personal_id',
            field=models.CharField(max_length=30),
        ),
    ]
